"""Add role to User

Revision ID: 11491c67f018
Revises: c7747c632f15
Create Date: 2025-05-17 02:28:57.480854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11491c67f018'
down_revision = 'c7747c632f15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
