"""Allow text-based time in plans

Revision ID: db71990616a3
Revises: 972efdef58c2
Create Date: 2025-05-24 05:38:13.659968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db71990616a3'
down_revision = '972efdef58c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.String(length=50),
               type_=postgresql.TIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
